# Robot Configuration Parameters - Kobuki
 max_vel_x: 0.3
 min_vel_x: 0.0

 max_trans_vel: 0.3
 min_trans_vel: 0.1
 tans_stopped_vel: 0.1

 max_rot_vel: 0.05
 min_rot_vel: 0.01 
 rot_stopped_vel: 0.01

 acc_lim_x: 0.1 
 acc_lim_theta: 0.1

 #goal tolerance
 yaw_goal_tolerance: 0.05
 xy_goal_tolerance: 0.10
 latch_xy_goal_tolerance: true

 #forward simulation params
 sim_time: 1.0
 vx_samples: 6
 vy_samples: 1
 vtheta_samples: 10


 path_distance_bias: 80.0
 goal_distance_bias: 60.0
 occdist_scale: 0.5
 forward_point_distance: 0.05
 stop_time_buffer: 0.2 
 scaling_speed: 0.05
 max_scaling_factor: 0.2  

 oscillation_reset_dist: 0.05

# Debugging
 publish_traj_pc: true
 publish_cost_grid_pc: true
 global_frame_id: odom

 #holonomic_robot: true

