// Generated by gencpp from file xbot_bringup/xbot_state.msg
// DO NOT EDIT!


#ifndef XBOT_BRINGUP_MESSAGE_XBOT_STATE_H
#define XBOT_BRINGUP_MESSAGE_XBOT_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbot_bringup
{
template <class ContainerAllocator>
struct xbot_state_
{
  typedef xbot_state_<ContainerAllocator> Type;

  xbot_state_()
    : power(0.0)  {
    }
  xbot_state_(const ContainerAllocator& _alloc)
    : power(0.0)  {
  (void)_alloc;
    }



   typedef float _power_type;
  _power_type power;




  typedef boost::shared_ptr< ::xbot_bringup::xbot_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbot_bringup::xbot_state_<ContainerAllocator> const> ConstPtr;

}; // struct xbot_state_

typedef ::xbot_bringup::xbot_state_<std::allocator<void> > xbot_state;

typedef boost::shared_ptr< ::xbot_bringup::xbot_state > xbot_statePtr;
typedef boost::shared_ptr< ::xbot_bringup::xbot_state const> xbot_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbot_bringup::xbot_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbot_bringup::xbot_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xbot_bringup

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'xbot_bringup': ['/home/howe/Xbot/src/xbot/xbot_bringup/msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xbot_bringup::xbot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbot_bringup::xbot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot_bringup::xbot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot_bringup::xbot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot_bringup::xbot_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot_bringup::xbot_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbot_bringup::xbot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b75f3bcdec2dcafb6503e9b6316400b0";
  }

  static const char* value(const ::xbot_bringup::xbot_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb75f3bcdec2dcafbULL;
  static const uint64_t static_value2 = 0x6503e9b6316400b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::xbot_bringup::xbot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbot_bringup/xbot_state";
  }

  static const char* value(const ::xbot_bringup::xbot_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbot_bringup::xbot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 power\n\
";
  }

  static const char* value(const ::xbot_bringup::xbot_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbot_bringup::xbot_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct xbot_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbot_bringup::xbot_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbot_bringup::xbot_state_<ContainerAllocator>& v)
  {
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBOT_BRINGUP_MESSAGE_XBOT_STATE_H
