// Generated by gencpp from file xbot_bringup/xbot_cmd.msg
// DO NOT EDIT!


#ifndef XBOT_BRINGUP_MESSAGE_XBOT_CMD_H
#define XBOT_BRINGUP_MESSAGE_XBOT_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbot_bringup
{
template <class ContainerAllocator>
struct xbot_cmd_
{
  typedef xbot_cmd_<ContainerAllocator> Type;

  xbot_cmd_()
    : cmd()
    , args()  {
    }
  xbot_cmd_(const ContainerAllocator& _alloc)
    : cmd(_alloc)
    , args(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _args_type;
  _args_type args;




  typedef boost::shared_ptr< ::xbot_bringup::xbot_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbot_bringup::xbot_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct xbot_cmd_

typedef ::xbot_bringup::xbot_cmd_<std::allocator<void> > xbot_cmd;

typedef boost::shared_ptr< ::xbot_bringup::xbot_cmd > xbot_cmdPtr;
typedef boost::shared_ptr< ::xbot_bringup::xbot_cmd const> xbot_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbot_bringup::xbot_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xbot_bringup

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'xbot_bringup': ['/home/howe/Xbot/src/xbot/xbot_bringup/msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbot_bringup::xbot_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot_bringup::xbot_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot_bringup::xbot_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6723d032225dfb791e3b4b487d839111";
  }

  static const char* value(const ::xbot_bringup::xbot_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6723d032225dfb79ULL;
  static const uint64_t static_value2 = 0x1e3b4b487d839111ULL;
};

template<class ContainerAllocator>
struct DataType< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbot_bringup/xbot_cmd";
  }

  static const char* value(const ::xbot_bringup::xbot_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cmd\n\
float32[] args\n\
";
  }

  static const char* value(const ::xbot_bringup::xbot_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.args);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct xbot_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbot_bringup::xbot_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbot_bringup::xbot_cmd_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
    s << indent << "args[]" << std::endl;
    for (size_t i = 0; i < v.args.size(); ++i)
    {
      s << indent << "  args[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.args[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBOT_BRINGUP_MESSAGE_XBOT_CMD_H
