// Generated by gencpp from file xbot_msgs/PowerSystemEvent.msg
// DO NOT EDIT!


#ifndef XBOT_MSGS_MESSAGE_POWERSYSTEMEVENT_H
#define XBOT_MSGS_MESSAGE_POWERSYSTEMEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbot_msgs
{
template <class ContainerAllocator>
struct PowerSystemEvent_
{
  typedef PowerSystemEvent_<ContainerAllocator> Type;

  PowerSystemEvent_()
    : event(0)  {
    }
  PowerSystemEvent_(const ContainerAllocator& _alloc)
    : event(0)  {
  (void)_alloc;
    }



   typedef uint8_t _event_type;
  _event_type event;


    enum { UNPLUGGED = 0u };
     enum { PLUGGED_TO_ADAPTER = 1u };
     enum { PLUGGED_TO_DOCKBASE = 2u };
     enum { CHARGE_COMPLETED = 3u };
     enum { BATTERY_LOW = 4u };
     enum { BATTERY_CRITICAL = 5u };
 

  typedef boost::shared_ptr< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> const> ConstPtr;

}; // struct PowerSystemEvent_

typedef ::xbot_msgs::PowerSystemEvent_<std::allocator<void> > PowerSystemEvent;

typedef boost::shared_ptr< ::xbot_msgs::PowerSystemEvent > PowerSystemEventPtr;
typedef boost::shared_ptr< ::xbot_msgs::PowerSystemEvent const> PowerSystemEventConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xbot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'xbot_msgs': ['/home/howe/Xbot/src/xbot/xbot_msgs/msg', '/home/howe/Xbot/devel/share/xbot_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6464657d6c911b00c7bc7b43a154bf8";
  }

  static const char* value(const ::xbot_msgs::PowerSystemEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6464657d6c911b0ULL;
  static const uint64_t static_value2 = 0x0c7bc7b43a154bf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbot_msgs/PowerSystemEvent";
  }

  static const char* value(const ::xbot_msgs::PowerSystemEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Power system events\n\
# This message is generated by important changes in the power system:\n\
#  - plug/unplug to the docking base or adapter\n\
#  - transitions to low/critical battery levels\n\
#  - battery charge completed\n\
\n\
uint8 UNPLUGGED           = 0\n\
uint8 PLUGGED_TO_ADAPTER  = 1\n\
uint8 PLUGGED_TO_DOCKBASE = 2\n\
uint8 CHARGE_COMPLETED    = 3\n\
uint8 BATTERY_LOW         = 4\n\
uint8 BATTERY_CRITICAL    = 5\n\
\n\
uint8 event\n\
";
  }

  static const char* value(const ::xbot_msgs::PowerSystemEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PowerSystemEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbot_msgs::PowerSystemEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbot_msgs::PowerSystemEvent_<ContainerAllocator>& v)
  {
    s << indent << "event: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.event);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBOT_MSGS_MESSAGE_POWERSYSTEMEVENT_H
